
CREATE TABLE TASK (
    ID NUMBER GENERATED ALWAYS AS IDENTITY,
    TITLE VARCHAR2(100) NOT NULL,
    DESCRIPTION VARCHAR2(500),
    STATUS VARCHAR2(20) NOT NULL,
    CREATION_DATE TIMESTAMP NOT NULL,

    CONSTRAINT PK_TASK PRIMARY KEY(ID)
);